add_cxxflags("-march=native", {tools = {"clang", "gcc"}})
add_cxxflags("-Wno-c++98-compat", {tools = {"clang"}, force=true})
add_requires("vcpkg::catch2 3.6.0")

target("test")
    set_kind("binary")
    set_filename("fluxpp_test")
    add_packages("vcpkg::catch2")
    set_targetdir(".")
    set_default(true)
    add_files("src/*.cpp")
    set_warnings("all")
--    set_optimize("fastest")
    set_languages("cxx17")
    add_includedirs("include",".")
--    add_links("Catch2Main", "Catch2" )
    add_files("test/*.cpp")
